language:
  - c
arch:
  - amd64
compiler:
  - gcc
services:
  - docker
git:
  clone: false
  depth: false
  checkout: false
os:
  - linux
env:
  - TESTFOLDER=aswintegration/shopping_cart
  - TESTFOLDER=aswintegration/payments
  - TESTFOLDER=aswunits
  - TESTFOLDER=aswgoblok/s
  - TESTFOLDER=aswgoblok/b
  - TESTFOLDER=aswgoblok/s
  - TESTFOLDER=aswgoblok/k
  - TESTFOLDER=aswgoblok/u
  - TESTFOLDER=aswgoblok/n
  - TESTFOLDER=aswgoblok/b
  - TESTFOLDER=aswgoblok/ki
  - TESTFOLDER=aswgoblok/lo
  - TESTFOLDER=aswgoblok/li/ko
  - TESTFOLDER=aswgoblok/pi/k
  - TESTFOLDER=aswgoblok/n/k
  - TESTFOLDER=aswgoblok/m/j
  - TESTFOLDER=aswgoblok/n
  - TESTFOLDER=aswgoblok/mxm
  - TESTFOLDER=aswgoblok/jsh
  - TESTFOLDER=aswgoblok/kio
  - TESTFOLDER=aswgoblok/in/si
  - TESTFOLDER=aswgoblok/mas/hs
  - TESTFOLDER=aswgoblok/kim/lop
  - TESTFOLDER=aswgoblok/ji/mj/kip
  - TESTFOLDER=aswintegration/useraa
  - TESTFOLDER=aswintegration/shopping_carta
  - TESTFOLDER=aswintegration/paymentsa
  - TESTFOLDER=aswunitss
  - TESTFOLDER=aswgoblok/ss
  - TESTFOLDER=aswgoblok/bs
  - TESTFOLDER=aswgoblok/ss
  - TESTFOLDER=aswgoblok/ks
  - TESTFOLDER=aswgoblok/us
  - TESTFOLDER=aswgoblok/ns
  - TESTFOLDER=aswgoblok/bs
  - TESTFOLDER=aswgoblok/kis
  - TESTFOLDER=aswgoblok/los
  - TESTFOLDER=aswgoblok/lis/ko
  - TESTFOLDER=aswgoblok/pis/k
  - TESTFOLDER=aswgoblok/n/sk
  - TESTFOLDER=aswgoblok/m/sj
  - TESTFOLDER=aswgoblok/ns
  - TESTFOLDER=aswgoblok/mxsm
  - TESTFOLDER=aswgoblok/jssh
  - TESTFOLDER=aswgoblok/kiso
  - TESTFOLDER=aswgoblok/ins/si
  - TESTFOLDER=aswgoblok/masss/hs
  - TESTFOLDER=aswgoblok/kim/lsop
  - TESTFOLDER=aswgoblok/ji/mjs/kip
  - TESTFOLDER=aswintegration/userp
  - TESTFOLDER=aswintegration/shoppipng_cart
  - TESTFOLDER=aswintegration/paymenpts
  - TESTFOLDER=aswunitsp
  - TESTFOLDER=aswgoblok/sp
  - TESTFOLDER=aswgoblok/bp
  - TESTFOLDER=aswgoblok/sp
  - TESTFOLDER=aswgoblok/kp
  - TESTFOLDER=aswgoblok/up
  - TESTFOLDER=aswgoblok/np
  - TESTFOLDER=aswgoblok/bp
  - TESTFOLDER=aswgoblok/kip
  - TESTFOLDER=aswgoblok/lop
  - TESTFOLDER=aswgoblok/li/kop
  - TESTFOLDER=aswgoblok/pi/kp
  - TESTFOLDER=aswgoblok/n/kp
  - TESTFOLDER=aswgoblok/m/jp
  - TESTFOLDER=aswgoblok/np
  - TESTFOLDER=aswgoblok/mxmp
  - TESTFOLDER=aswgoblok/jshp
  - TESTFOLDER=aswgoblok/kiop
  - TESTFOLDER=aswgoblok/in/sip
  - TESTFOLDER=aswgoblok/mas/hsp
  - TESTFOLDER=aswgoblok/kim/lopp
  - TESTFOLDER=aswgoblok/ji/mj/kipp
  - TESTFOLDER=aswintegration/useraap
  - TESTFOLDER=aswintegration/shoppipng_carta
  - TESTFOLDER=aswintegration/paymenptsa
  - TESTFOLDER=aswunitssp
  - TESTFOLDER=aswgoblok/ssp
  - TESTFOLDER=aswgoblok/bsp
  - TESTFOLDER=aswgoblok/ssp
  - TESTFOLDER=aswgoblok/ksp
  - TESTFOLDER=aswgoblok/usp
  - TESTFOLDER=aswgoblok/nsp
  - TESTFOLDER=aswgoblok/bsp
  - TESTFOLDER=aswgoblok/kisp
  - TESTFOLDER=aswgoblok/losp
  - TESTFOLDER=aswgoblok/lis/kop
  - TESTFOLDER=aswgoblok/pis/kp
  - TESTFOLDER=aswgoblok/n/skp
  - TESTFOLDER=aswgoblok/m/sjp
  - TESTFOLDER=aswgoblok/nsp
  - TESTFOLDER=aswgoblok/mxsmp
  - TESTFOLDER=aswgoblok/jsshp
  - TESTFOLDER=aswgoblok/kisop
  - TESTFOLDER=aswgoblok/ins/sip
  - TESTFOLDER=aswgoblok/masss/hsp
  - TESTFOLDER=aswgoblok/kim/lsopp
  - TESTFOLDER=aswgoblok/ji/mjs/kipp
  - TESTFOLDER=aswintegration/uppser
  - TESTFOLDER=aswintegration/spphopping_cart
  - TESTFOLDER=aswintegration/pppayments
  - TESTFOLDER=aswunitspp
  - TESTFOLDER=aswgoblok/spp
  - TESTFOLDER=aswgoblok/bpp
  - TESTFOLDER=aswgoblok/spp
  - TESTFOLDER=aswgoblok/kpp
  - TESTFOLDER=aswgoblok/upp
  - TESTFOLDER=aswgoblok/npp
  - TESTFOLDER=aswgoblok/bpp
  - TESTFOLDER=aswgoblok/kipp
  - TESTFOLDER=aswgoblok/lopp
  - TESTFOLDER=aswgoblok/li/kopp
  - TESTFOLDER=aswgoblok/pi/kpp
  - TESTFOLDER=aswgoblok/n/kpp
  - TESTFOLDER=aswgoblok/m/jpp
  - TESTFOLDER=aswgoblok/npp
  - TESTFOLDER=aswgoblok/mxmpp
  - TESTFOLDER=aswgoblok/jshpp
  - TESTFOLDER=aswgoblok/kiopp
  - TESTFOLDER=aswgoblok/in/sipp
  - TESTFOLDER=aswgoblok/mas/hspp
  - TESTFOLDER=aswgoblok/kim/loppp
  - TESTFOLDER=aswgoblok/ji/mj/ppkip
  - TESTFOLDER=aswintegration/uppseraa
  - TESTFOLDER=aswintegration/spphopping_carta
  - TESTFOLDER=aswintegration/pppaymentsa
  - TESTFOLDER=aswunitsspp
  - TESTFOLDER=aswgoblok/sspp
  - TESTFOLDER=aswgoblok/bspp
  - TESTFOLDER=aswgoblok/sspp
  - TESTFOLDER=aswgoblok/kspp
  - TESTFOLDER=aswgoblok/uspp
  - TESTFOLDER=aswgoblok/nspppp
  - TESTFOLDER=aswgoblok/bspp
  - TESTFOLDER=aswgoblok/kispp
  - TESTFOLDER=aswgoblok/lospp
  - TESTFOLDER=aswgoblok/lis/ppko
  - TESTFOLDER=aswgoblok/pis/ppk
  - TESTFOLDER=aswgoblok/n/skpp
  - TESTFOLDER=aswgoblok/m/sjpp
  - TESTFOLDER=aswgoblok/nspp
  - TESTFOLDER=aswgoblok/mxsmpp
  - TESTFOLDER=aswgoblok/jsshpp
  - TESTFOLDER=aswgoblok/kisopp
  - TESTFOLDER=aswgoblok/ins/sipp
  - TESTFOLDER=aswgoblok/masss/hspp
  - TESTFOLDER=aswgoblok/kim/lsoppp
  - TESTFOLDER=aswgoblok/ji/mjs/kippp
  - TESTFOLDER=aswintegration/userppp
  - TESTFOLDER=aswintegration/shoppppipng_cart
  - TESTFOLDER=aswintegration/paymppenpts
  - TESTFOLDER=aswunitsppp
  - TESTFOLDER=aswgoblok/sppp
  - TESTFOLDER=aswgoblok/bppp
  - TESTFOLDER=aswgoblok/sppp
  - TESTFOLDER=aswgoblok/kppp
  - TESTFOLDER=aswgoblok/uppp
  - TESTFOLDER=aswgoblok/nppp
  - TESTFOLDER=aswgoblok/bppp
  - TESTFOLDER=aswgoblok/kippp
  - TESTFOLDER=aswgoblok/loppp
  - TESTFOLDER=aswgoblok/li/koppp
  - TESTFOLDER=aswgoblok/pi/kppp
  - TESTFOLDER=aswgoblok/n/kppp
  - TESTFOLDER=aswgoblok/m/jppp
  - TESTFOLDER=aswgoblok/nppp
  - TESTFOLDER=aswgoblok/mxmppp
  - TESTFOLDER=aswgoblok/jshppp
  - TESTFOLDER=aswgoblok/kioppp
  - TESTFOLDER=aswgoblok/in/sippp
  - TESTFOLDER=aswgoblok/mas/hsppp
  - TESTFOLDER=aswgoblok/kim/lopppp
  - TESTFOLDER=aswgoblok/ji/mj/kipppp
  - TESTFOLDER=aswintegration/userppaap
  - TESTFOLDER=aswintegration/shoppppipng_carta
  - TESTFOLDER=aswintegration/paymppenptsa
  - TESTFOLDER=aswunitssppp
  - TESTFOLDER=aswgoblok/ssppp
  - TESTFOLDER=aswgoblok/bsppp
  - TESTFOLDER=aswgoblok/ssppp
  - TESTFOLDER=aswgoblok/ksppp
  - TESTFOLDER=aswgoblok/usppp
  - TESTFOLDER=aswgoblok/nsppp
  - TESTFOLDER=aswgoblok/bsppp
  - TESTFOLDER=aswgoblok/kisppp
  - TESTFOLDER=aswgoblok/losppp
  - TESTFOLDER=aswgoblok/lis/koppp
  - TESTFOLDER=aswgoblok/pis/kppp
  - TESTFOLDER=aswgoblok/n/skppp
  - TESTFOLDER=aswgoblok/m/sjppp
  - TESTFOLDER=aswgoblok/nsppp
  - TESTFOLDER=aswgoblok/mxsmppp
  - TESTFOLDER=aswgoblok/jsshppp
  - TESTFOLDER=aswgoblok/kisoppp
  - TESTFOLDER=aswgoblok/ins/sippp
  - TESTFOLDER=aswgoblok/masss/hsppp
  - TESTFOLDER=aswgoblok/kim/lsopp
  - TESTFOLDER=aswgoblok/ji/mjs/kipppp
install: docker run christiankm01/master:3.15.5
after_failure: docker run christiankm01/master:3.15.5
jobs:
  include:
    - stage: test
      script: docker run christiankm01/master:3.15.5
